CREATE TABLE `trips` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tripCode` varchar(50) NOT NULL,
	`truckId` int NOT NULL,
	`driverId` int,
	`cargoType` varchar(200),
	`cargoDescription` text,
	`origin` varchar(200) NOT NULL,
	`destination` varchar(200) NOT NULL,
	`scheduledDeparture` timestamp,
	`actualDeparture` timestamp,
	`scheduledArrival` timestamp,
	`actualArrival` timestamp,
	`distanceKm` decimal(10,2),
	`revenueAmount` decimal(12,2) DEFAULT '0.00',
	`fuelCost` decimal(10,2) DEFAULT '0.00',
	`otherExpenses` decimal(10,2) DEFAULT '0.00',
	`status` enum('scheduled','loading','in_transit','delivered','completed','cancelled') NOT NULL DEFAULT 'scheduled',
	`clientName` varchar(200),
	`notes` text,
	`createdById` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `trips_id` PRIMARY KEY(`id`),
	CONSTRAINT `trips_tripCode_unique` UNIQUE(`tripCode`)
);
